{{- if eq (include "nidus.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nidus.fullname" . }}
  labels:
    {{- include "nidus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.auth.enabled .Values.auth.token (not .Values.auth.existingSecret) }}
  NIDUS_TOKEN: {{ .Values.auth.token | quote }}
  {{- end }}
  {{- range $k, $v := .Values.credentials.inline }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
